### ISSUE TITLE
Publish on npm via @types for Typescript 2

### ISSUE THREAD

**Issue by schickling** [nitintutlani/typed-graphql#13]

**Comment by nitintutlani** [comment]
PR requested.

**Comment by pcarrier** [comment]
@nitintutlani link?

**Comment by jperl** [comment]
I submitted a PR and published it to npm. See here https://github.com/nitintutlani/typed-graphql/issues/16

**Comment by kylecordes** [comment]
To help anyone else who arrives here from a search: the above effort succeeded, you can now perform the standard `npm i @types/graphql`.
