### ISSUE TITLE
Publishing a new version

### ISSUE THREAD

**Issue by DxCx** [nitintutlani/typed-graphql#25]
Hi can you please publish a new npm version after merging #24 ?

**Comment by nitintutlani** [comment]
done

**Comment by kamilkisiela** [comment]
There is no new version in npm.

From `npm info graphql-typings`

```
0.0.1-beta: 2016-08-17T21:04:52.162Z
0.0.1-beta-1: 2016-08-17T21:07:18.588Z,
0.0.1-beta-2: 2016-08-17T21:08:57.473Z
```

@nitintutlani Could you publish new version to npm? We need this here apollostack/apollo-client#656

**Comment by nitintutlani** [comment]
Please try `npm info typed-graphql`

**Comment by DxCx** [comment]
See the comment i left for you on your issue :)
Package was renamed to typed-graphql

**Comment by kamilkisiela** [comment]
Thanks

**Comment by DxCx** [comment]
Hi @nitintutlani can you please publish another version? there is one more patch added.
