### ISSUE TITLE
Would you push to definitelytyped?

### ISSUE THREAD

**Issue by TonyPythoneer** [nitintutlani/typed-graphql#28]
Hello, @DxCx 

I had noticed this repo. It looks very good!

I hope this repo can push to definitelytyped.

I look forward to your response. :smile:

**Comment by DxCx** [comment]
Hi @TonyPythoneer :)

Actually im not the owner of the repo just a contributer..

But if @nitintutlani doesnt mind, i can open a PR on DT, however from my experience with DT they take forever to approve and add typings  (had a PR open there for more then one month)  so i dont know when it will be avliable after the push

**Comment by nitintutlani** [comment]
We are already on the typings tool. `typings install graphql` , with time the shift is to push typings directly into npm packages wherever possible.

Still, please feel free to take any steps further.

**Comment by TonyPythoneer** [comment]
Okay, I expect it can install by **typings install graphql** in the future. :smile:

**Comment by DxCx** [comment]
@TonyPythoneer i was just about to do it and then i saw DefinitelyTyped/DefinitelyTyped#11598
are those the same typings?
are you taking this?

**Comment by TonyPythoneer** [comment]
No, those are different typings. `typed-graphql` offers all typings of sub modules in the main module. My defintion is able to call not only the main module but also the specified sub module.

When I built my defintion, I wasn't taking `typed-graphql`. It's because I don't like all properties, interfaces, classes, functions gather up into single namespace. I know although it's very convenient when invoking anything of main module, `graphql` is a big project, it needs to modular each sub module to improve readability and maintainability. So, I fully refer to source code and way. I hope it keep intact in each module, whether it's a `flow-type`  or `typescript` developer, they will get same development experience.

But it's still incomplete, I have no time to complete `graphql/utilities` and `graphql-tests.d.ts`. If you find it has a deficiency, please send PR and add your name in authors. I believe `typed-graphql` contributors are experienced about it.
