### ISSUE TITLE
Make it available under '@types/graphql'

### ISSUE THREAD

**Issue by zsfarkas** [nitintutlani/typed-graphql#30]
It would be so nice to have this definition under @types/graphql.

But maybe I am wrong and this project does not fit to there.

**Comment by zsfarkas** [comment]
Sorry. I don't know, why I could not see it.

I think it was a typo in 'npm install'.

So it can be closed.

**Comment by kylecordes** [comment]
To help anyone else who arrives here from a search:  This has been done, you can now perform the standard `npm i @types/graphql`.

**Comment by nitintutlani** [comment]
Very good contribution
