### ISSUE TITLE
Consider moving this to DefinitelyTyped project

### ISSUE THREAD

**Issue by baloodevil** [nitintutlani/typed-graphql#6]
IMHO it would be better to have all type definitions live in a single repository, and the de facto standard spot is: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by nitintutlani** [comment]
This repo is suitable for now.

**Comment by mnpenner** [comment]
I don't want to create a new ticket for this, so a note to others, you can install this with [typings](https://www.npmjs.com/package/typings):

``` bash
sudo npm install -g typings
typings install 'github:nitintutlani/typed-graphql'
```

**Comment by blakeembrey** [comment]
@nitintutlani This repo has been brought up on the Typings registry. I agree, merging into DefinitelyTyped is a mess - but the Typings registry works by having pointers to other people's typings, just like this. Would you mind if we add a reference to this project for people installing GraphQL?

**Comment by nitintutlani** [comment]
No issues. Plz update me if any action is required at my end.
